// 📂 src/constants.js
export const initialProducts = [
  {
    id: 1,
    name: 'চাল (মিনিকেট)',
    nameEn: 'Miniket Rice',
    category: 'শস্য',
    unit: 'কেজি',
    price: 72,
    prevPrice: 68,
    icon: '🌾',
  },
  {
    id: 2,
    name: 'আটা',
    nameEn: 'Wheat Flour',
    category: 'শস্য',
    unit: 'কেজি',
    price: 55,
    prevPrice: 58,
    icon: '🌾',
  },
  {
    id: 3,
    name: 'ডাল (মসুর)',
    nameEn: 'Lentils',
    category: 'ডাল',
    unit: 'কেজি',
    price: 130,
    prevPrice: 125,
    icon: '🫘',
  },
  {
    id: 4,
    name: 'সয়াবিন তেল',
    nameEn: 'Soybean Oil',
    category: 'তেল',
    unit: 'লিটার',
    price: 168,
    prevPrice: 175,
    icon: '🫙',
  },
  {
    id: 5,
    name: 'পেঁয়াজ',
    nameEn: 'Onion',
    category: 'সবজি',
    unit: 'কেজি',
    price: 90,
    prevPrice: 80,
    icon: '🧅',
  },
  {
    id: 6,
    name: 'রুই মাছ',
    nameEn: 'Rohu Fish',
    category: 'মাছ',
    unit: 'কেজি',
    price: 280,
    prevPrice: 260,
    icon: '🐟',
  },
];

export const categories = [
  'সব',
  'শস্য',
  'ডাল',
  'তেল',
  'সবজি',
  'মাংস',
  'মাছ',
  'দুগ্ধ',
  'মশলা',
];
